# backend/app/core/models/feedback.py

"""
Feedback reports collection models.
Enhanced with learning insights, revision suggestions, and personalization.
"""

from datetime import datetime
from typing import List, Optional, Dict
from pydantic import BaseModel
from .base import MongoBaseModel, PyObjectId


# ============================
# REVISION RECOMMENDATION
# ============================

class RevisionItem(BaseModel):
    """Specific content recommendation for revision."""
    
    concept: str
    reason: str  # Why this needs revision
    priority: str  # "high" | "medium" | "low"
    
    # Linked resources
    source_file: Optional[str] = None  # From notes
    chapter_number: Optional[int] = None
    section: Optional[str] = None
    
    # Study suggestions
    estimated_time: Optional[float] = None  # Minutes
    recommended_approach: Optional[str] = None  # "review_notes" | "practice_questions" | "tutorial"


# ============================
# CONCEPT ANALYSIS
# ============================

class ConceptAnalysis(BaseModel):
    """Detailed analysis of a concept's mastery."""
    
    concept: str
    
    # Performance
    questions_on_concept: int
    correct_answers: int
    accuracy_percentage: float
    
    # Classification
    mastery_level: str  # "strong" | "developing" | "needs_attention"
    
    # Recommendations
    needs_revision: bool
    suggestion: str


# ============================
# LEARNING INSIGHT
# ============================

class LearningInsight(BaseModel):
    """Actionable insight from performance analysis."""
    
    insight_type: str  # "strength" | "weakness" | "pattern" | "recommendation"
    title: str
    description: str
    action_items: List[str] = []


# ============================
# FEEDBACK REPORT
# ============================

class FeedbackReport(MongoBaseModel):
    """
    Comprehensive feedback report generated by Feedback Agent.
    
    Created after quiz completion, provides:
    - Performance analysis
    - Strengths and weaknesses
    - Personalized revision plan
    - Motivational guidance
    """
    
    # References
    user_id: PyObjectId
    quiz_result_id: PyObjectId
    quiz_id: PyObjectId
    subject_id: PyObjectId
    session_id: Optional[PyObjectId] = None
    
    # Assessment type
    assessment_type: str  # "quiz" | "revision" | "mock_exam" | "adaptive"
    
    # Score summary
    score: float
    max_score: float
    percentage: float
    performance_level: str  # "excellent" | "good" | "satisfactory" | "needs_improvement"
    
    # Performance analysis
    performance_summary: str  # Overall assessment
    
    # Strengths (concepts with >80% accuracy)
    strengths: List[str]
    strength_details: List[ConceptAnalysis] = []
    
    # Weak areas (concepts with <60% accuracy)
    weak_areas: List[str]
    weakness_details: List[ConceptAnalysis] = []
    
    # Revision plan
    revision_tips: List[str]
    revision_items: List[RevisionItem] = []
    estimated_revision_time: Optional[float] = None  # Hours
    
    # Recommended resources (from Content Agent)
    recommended_resources: List[str] = []
    recommended_chapters: List[int] = []
    
    # Learning insights
    insights: List[LearningInsight] = []
    
    # Motivational content
    motivational_message: str
    encouragement: str = ""
    
    # Progress context
    overall_progress: Optional[Dict] = None  # From PlannerService
    progress_change: Optional[str] = None  # "improving" | "stable" | "declining"
    
    # Next steps
    next_steps: List[str] = []
    suggested_next_topic: Optional[str] = None
    
    # Impact on study plan
    study_plan_updated: bool = False  # True if PlannerService was notified
    schedule_adjustments: List[str] = []  # Changes made to study plan
    
    # Metadata
    generated_by: str = "feedback_agent"
    processing_time: Optional[float] = None  # Seconds
    
    created_at: datetime = datetime.utcnow()


# ============================
# FEEDBACK SUMMARY (for UI)
# ============================

class FeedbackSummary(BaseModel):
    """Lightweight feedback summary for UI display."""
    
    quiz_title: str
    score_percentage: float
    performance_level: str
    
    top_strengths: List[str]  # Top 3
    top_weaknesses: List[str]  # Top 3
    
    key_message: str
    next_action: str


# ============================
# BATCH FEEDBACK ANALYSIS
# ============================

class BatchFeedbackAnalysis(BaseModel):
    """
    Aggregated feedback across multiple quizzes.
    Used for long-term trend analysis.
    """
    
    user_id: str
    subject_id: str
    
    # Time range
    start_date: datetime
    end_date: datetime
    
    # Aggregated metrics
    total_quizzes: int
    average_score: float
    score_trend: str  # "improving" | "stable" | "declining"
    
    # Persistent patterns
    consistent_strengths: List[str]
    persistent_weaknesses: List[str]
    
    # Recommendations
    focus_areas: List[str]
    mastery_progress: Dict[str, float]  # concept → improvement %